version: '3.8'

services:
  # React Frontend (Production)
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: react-app
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "80:80"
    networks:
      - react-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  react-network:
    driver: bridge