version: '3.8'

services:
  # React Frontend (Development mode with hot reload)
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react-app-dev
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "3001:3001"
    networks:
      - react-network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3001

networks:
  react-network:
    driver: bridge